# Generated by Django 5.2.18 on 2026-10-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de personas.')),
                ('tarifa', models.PositiveIntegerField(default=0, help_text='Pesos chilenos por reserva (0 = gratis).')),
                ('hora_apertura', models.TimeField(default='09:00')),
                ('hora_cierre', models.TimeField(default='22:00')),
                ('activo', models.BooleanField(default=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'espacio común',
                'verbose_name_plural': 'espacios comunes',
                'ordering': ['condominio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora de término')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.espaciocomun')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='condominios.unidad')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='espaciocomun',
            constraint=models.UniqueConstraint(fields=('condominio', 'nombre'), name='uq_espacio_nombre'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['espacio', 'fecha'], name='reservas_re_espacio_3113c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_reserva_horario'),
        ),
    ]
