# Generated by Django 5.2.18 on 2026-10-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('mensaje', models.TextField()),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='enlace')),
                ('leida', models.BooleanField(default=False, verbose_name='leída')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='condominios.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-creada'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx')],
            },
        ),
    ]
