# Generated by Django 5.2.18 on 2026-10-06 19:38

import apps.notificaciones.observador
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MANTENCION', 'Mantención / reparación'), ('SEGURIDAD', 'Seguridad'), ('RUIDOS', 'Ruidos molestos'), ('ASEO', 'Aseo'), ('AREAS_COMUNES', 'Áreas comunes'), ('OTRO', 'Otro')], max_length=20, verbose_name='categoría')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto')], default='RECIBIDO', max_length=20)),
                ('respuesta', models.TextField(blank=True, help_text='Comentario de la administración para el residente.')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='fecha de reporte')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='condominios.condominio')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, help_text='Unidad afectada (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='condominios.unidad')),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
            bases=(apps.notificaciones.observador.Sujeto, models.Model),
        ),
    ]
