# Generated by Django 5.2.18 on 2026-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recibir_correos',
            field=models.BooleanField(default=True, help_text='Comunicados, incidentes, gastos comunes emitidos y pagos registrados.', verbose_name='recibir avisos por correo'),
        ),
    ]
