# Generated by Django 5.2.18 on 2026-10-09 22:26

import apps.notificaciones.observador
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0004_unidad_restrict_cobros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('medio', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('WEBPAY', 'Webpay')], default='TRANSFERENCIA', max_length=15)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gastos.detallegastocomun')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
            bases=(apps.notificaciones.observador.Sujeto, models.Model),
        ),
    ]
