# Generated by Django 5.2.18 on 2026-10-06 19:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=200, verbose_name='dirección')),
                ('comuna', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='condominios.condominio')),
            ],
            options={
                'ordering': ['condominio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COMITE', 'Comité de administración'), ('RESIDENTE', 'Residente'), ('CONSERJE', 'Conserje')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('desde', models.DateField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='condominios.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='número')),
                ('piso', models.SmallIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('DEPARTAMENTO', 'Departamento'), ('CASA', 'Casa'), ('LOCAL', 'Local comercial'), ('ESTACIONAMIENTO', 'Estacionamiento'), ('BODEGA', 'Bodega')], default='DEPARTAMENTO', max_length=20)),
                ('alicuota', models.DecimalField(decimal_places=6, help_text='Fracción del total (ej. 0.012500 = 1,25 %).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='alícuota')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominios.edificio')),
            ],
            options={
                'verbose_name_plural': 'unidades',
                'ordering': ['edificio', 'piso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ARRENDATARIO', 'Arrendatario'), ('FAMILIAR', 'Familiar / otro ocupante')], default='PROPIETARIO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='condominios.unidad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='edificio',
            constraint=models.UniqueConstraint(fields=('condominio', 'nombre'), name='uq_edificio_nombre'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('usuario', 'condominio', 'rol'), name='uq_membresia_rol'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('edificio', 'numero'), name='uq_unidad_numero'),
        ),
        migrations.AddConstraint(
            model_name='residente',
            constraint=models.UniqueConstraint(fields=('usuario', 'unidad'), name='uq_residente_unidad'),
        ),
    ]
