# Generated by Django 5.2.18 on 2026-10-08 01:45

import apps.cuentas.validadores
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, validators=[apps.cuentas.validadores.validar_rut], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=150, verbose_name='razón social')),
                ('rubro', models.CharField(help_text='Ej.: ascensores, jardinería, aseo.', max_length=80)),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['razon_social'],
                'constraints': [models.UniqueConstraint(fields=('condominio', 'rut'), name='proveedor_rut_unico_por_condominio')],
            },
        ),
    ]
