# Generated by Django 5.2.18 on 2026-10-07 03:21

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EMITIDO', 'Emitido')], default='ABIERTO', max_length=10)),
                ('porcentaje_fondo_reserva', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Mínimo 5 % (Ley 21.442).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('5')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='% fondo de reserva')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_gasto', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'período de gastos',
                'verbose_name_plural': 'períodos de gastos',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('REMUNERACIONES', 'Remuneraciones'), ('CONSUMOS', 'Consumos básicos (luz, agua, gas)'), ('MANTENCION', 'Mantención y reparaciones'), ('ASEO', 'Aseo'), ('SEGURIDAD', 'Seguridad'), ('ADMINISTRACION', 'Administración'), ('OTROS', 'Otros')], max_length=20, verbose_name='categoría')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripción')),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('fecha', models.DateField(default=datetime.date.today, help_text='Fecha de la boleta o factura.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos_registrados', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='gastos.periodogasto')),
            ],
            options={
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodogasto',
            constraint=models.UniqueConstraint(fields=('condominio', 'anio', 'mes'), name='uq_periodo_mes'),
        ),
    ]
