# Generated by Django 5.2.18 on 2026-10-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleGastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('monto_fondo_reserva', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('MOROSO', 'Moroso')], default='PENDIENTE', max_length=10)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gastos.periodogasto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='condominios.unidad')),
            ],
            options={
                'verbose_name': 'detalle de gasto común',
                'verbose_name_plural': 'detalles de gastos comunes',
                'ordering': ['periodo', 'unidad'],
                'constraints': [models.UniqueConstraint(fields=('periodo', 'unidad'), name='uq_detalle_periodo_unidad')],
            },
        ),
    ]
