# Generated by Django 5.2.18 on 2026-10-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_detalle_gasto_comun'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodogasto',
            name='criterio_prorrateo',
            field=models.CharField(choices=[('ALICUOTA', 'Según la alícuota de cada unidad (Ley 21.442)'), ('PARTES_IGUALES', 'En partes iguales')], default='ALICUOTA', help_text='Por defecto, según la alícuota. Usa otro solo si el reglamento del condominio lo indica.', max_length=20, verbose_name='criterio de prorrateo'),
        ),
        migrations.AddField(
            model_name='periodogasto',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de emisión'),
        ),
    ]
