# Generated by Django 5.2.18 on 2026-10-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('gastos', '0003_criterio_y_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallegastocomun',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cobros', to='condominios.unidad'),
        ),
    ]
