# Generated by Django 5.2.18 on 2026-10-06 19:38

import apps.notificaciones.observador
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('GENERAL', 'General (todo el condominio)'), ('POR_EDIFICIO', 'Solo un edificio')], default='GENERAL', max_length=20)),
                ('fijado', models.BooleanField(default=False, help_text='Los fijados aparecen primero.')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='condominios.condominio')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='condominios.edificio')),
            ],
            options={
                'ordering': ['-fijado', '-fecha_publicacion'],
            },
            bases=(apps.notificaciones.observador.Sujeto, models.Model),
        ),
    ]
